# Generated by Django 5.1.6 on 2025-03-18 23:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='date_completed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='website.habit'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'date_completed')},
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
