# Generated by Django 5.1.6 on 2025-03-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_habit_active_habit_last_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[(1, 'Daily'), (7, 'Weekly'), (30, 'Monthly')], max_length=10),
        ),
    ]
