# Generated by Django 5.1.6 on 2025-03-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_habit_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
    ]
