# Generated by Django 5.1.6 on 2025-03-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_habit_current_streak_habit_max_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
