# Generated by Django 5.1.6 on 2025-04-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_custom_user_profile_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='profile_link',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='rank',
            field=models.CharField(default='Earthling - Earth', max_length=100),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='total_exp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
