# Generated by Django 5.1.6 on 2025-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_custom_user_profile_link_custom_user_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='custom_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='experience',
            field=models.IntegerField(choices=[(100, '100 XP'), (200, '200 XP'), (500, '500 XP'), (1000, '1000 XP'), (-1, 'Custom XP')], default=100),
        ),
    ]
