# Generated by Django 5.1.6 on 2025-04-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_habit_custom_experience_habit_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='experience',
            field=models.IntegerField(choices=[(100, '100 XP'), (200, '200 XP'), (500, '500 XP'), (1000, '1000 XP'), (-1, 'Custom XP')]),
        ),
    ]
