# Generated by Django 5.1.6 on 2025-04-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_habit_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='reminder_monthly',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_weekly',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='rank',
            field=models.CharField(choices=[('Earthling', 'Earthling'), ('Skyward Wanderer', 'Skyward Wanderer'), ('Lunar Explorer', 'Lunar Explorer'), ('Martian Scout', 'Martian Scout'), ('Storm Rider', 'Storm Rider'), ('Ring Voyager', 'Ring Voyager'), ('Ice Drifter', 'Ice Drifter'), ('Deep Diver', 'Deep Diver'), ('Galactic Traveler', 'Galactic Traveler'), ('Singularity Seeker', 'Singularity Seeker'), ('Starborn Survivor', 'Starborn Survivor'), ('Intergalactic Navigator', 'Intergalactic Navigator')], default='Earthling', max_length=100),
        ),
    ]
