# Generated by Django 5.1.6 on 2025-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_habit_reminder_monthly_habit_reminder_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
