# Generated by Django 5.1.6 on 2025-04-17 20:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_custom_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitSkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_skipped', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(blank=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='website.habit')),
            ],
            options={
                'unique_together': {('habit', 'date_skipped')},
            },
        ),
    ]
