# Generated by Django 5.1.6 on 2025-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_habitskip'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
