# Generated by Django 5.1.6 on 2025-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='last_spin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
