# Generated by Django 5.1.6 on 2025-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_streak_delete_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='consecutive_dates',
        ),
        migrations.AddField(
            model_name='streak',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='streak_length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
