# Generated by Django 5.1.6 on 2025-04-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_streak_consecutive_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='consecutive_logins',
            field=models.JSONField(default=list),
        ),
    ]
