# Generated by Django 5.1.6 on 2025-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_streak_consecutive_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='streak_rewards_claimed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Streak',
        ),
    ]
