# Generated by Django 5.1.6 on 2025-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_custom_user_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='last_spin_reward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
