# Generated by Django 5.1.6 on 2025-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_custom_user_last_spin_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='privacy_mode',
            field=models.BooleanField(default=True),
        ),
    ]
